/*
 * MCAL_EXTI_Config.h
 *
 *  Created on: Jun 24, 2022
 *      Author: Eng- Mohamed Mokhtar
 */

#ifndef MCAL_EXTI_MCAL_EXTI_CONFIG_H_
#define MCAL_EXTI_MCAL_EXTI_CONFIG_H_

/* EXTI0 SENSE MODE OPTIONS:
[1] LOW_LEVEL,		[2] RISING_EDGE,
[3] FALLING_EDGE,	[4] ANY_LOGICAL_CHANGE	*/
#define EXTINT_0_SENSE_CTRL_MODE    FALLING_EDGE

/* EXTI1 SENSE MODE OPTIONS:
[1] LOW_LEVEL,		[2] RISING_EDGE,
[3] FALLING_EDGE,	[4] ANY_LOGICAL_CHANGE	*/
#define EXTINT_1_SENSE_CTRL_MODE    FALLING_EDGE

/* EXTI2 SENSE MODE OPTIONS:
[1] FALLING_EDGE
[2] RISING_EDGE								*/
#define EXTINT_2_SENSE_CTRL_MODE    FALLING_EDGE

#endif /* MCAL_EXTI_MCAL_EXTI_CONFIG_H_ */
